juvonet_openapi.docs:
    path: /openapi/docs.json
    controller: Juvonet\OpenApiBundle\Controller\DocumentationAction
    methods: GET

juvonet_openapi.ui:
    path: /openapi
    controller: Juvonet\OpenApiBundle\Controller\IndexAction
    methods: GET
