juvonet_openapi.docs:
    path: /api/docs.json
    controller: Juvonet\OpenApiBundle\Controller\DocumentationAction
    methods: GET

juvonet_openapi.ui:
    path: /api
    controller: Juvonet\OpenApiBundle\Controller\IndexAction
    methods: GET
